[display]
compact = false
use_pager = false
show_title = false

[updates]
auto_update = true
auto_update_interval_hours = 720
archive_source = "https://github.com/tldr-pages/tldr/releases/latest/download/"
tls_backend = "native-tls"

[directories]

[search]
