s stop
q quit
Q quit-watch-later
p cycle pause
space cycle pause

. frame-step
, frame-back-step

l seek 2
h seek -2
L seek 30
H seek -30
g seek 0 absolute
G seek 100 absolute

ctrl+l sub-seek 1
Ctrl+h sub-seek -1

r ab-loop

[ playlist_prev
] playlist_next

} add chapter 1
{ add chapter -1

+ add volume 5
- add volume -5
m cycle mute

> add speed 0.1
< add speed -0.1
BS set speed 1.0

f cycle fullscreen
i show-progress
I script-binding stats/display-stats-toggle

v cycle sub
a cycle audio

Z sub-step 1
X sub-step -1
z add sub-delay 0.1
x add sub-delay -0.1
k set sub-delay 0

S screenshot
Alt+s screenshot video
Ctrl+s screenshot window

1 apply-profile integrated-gpu ; show-text "Integrated GPU Profile"
2 apply-profile dedicated-gpu ; show-text "Dedicated GPU Profile"
3 apply-profile anime4k-ultra ; show-text "Anime4K Ultra Profile"
