#! /bin/sh

bspc monitor -d 1 2 3 4 5 6 7

bspc config top_padding 0
bspc config bottom_padding 11

bspc config border_width 3
bspc config focused_border_color "#a6d189"
bspc config normal_border_color "#c7c7c7"

bspc config window_gap 10
bspc config split_ratio 0.50

bspc config gapless_monocle true
bspc config borderless_monocle true

bspc config focus_follows_pointer false

# app favorite desktop
bspc rule -a qBittorrent desktop=^7 follow=true
bspc rule -a mpv desktop=^5 state=floating follow=true
bspc rule -a vlc desktop=^5 state=floating follow=true
bspc rule -a obsidian desktop=^6 follow=off follow=true

# app favorite mode
bspc rule -a feh state=floating center=true
bspc rule -a pavucontrol state=floating center=true

xset -dpms                       # stay awake
xsetroot -cursor_name left_ptr & # fix mouse

~/.fehbg &
~/bin/sh/start-polybar.sh &

pipewire &
pipewire-pulse &
dunst &
mpd &
picom &

pgrep -x "wireplumber" >/dev/null || wireplumber &
pgrep -x "udiskie" >/dev/null || udiskie &
pgrep -x "unclutter" >/dev/null || unclutter &
pgrep -x "sxhkd" >/dev/null || sxhkd -m -1 &
