#!/usr/bin/sh

# override defaults
alias cd='z'
alias ls='eza'
alias cdi='zi'

# main
alias n="nvim"
alias :q="exit"
alias cl="clear"
alias yay="paru"
alias wg="sudo wg"
alias sudo="sudo "
alias pass="gopass"
alias bb="btm --basic"
alias vi="nvim --noplugin"
alias zshc="nvim ~/.zshrc"
alias zshe="nvim ~/.zshenv"
alias ani-cli="ani-cli -q 1080"
alias jjh="jj bookmark set main"
alias leetcode="nvim leetcode.nvim"
alias c="xclip -selection clipboard"
alias p="xclip -selection clipboard -o"
alias feh="feh -g 860x600 --scale-down"
alias xr="nvim --noplugin ~/.Xresources"
alias ani-cli-dub="ani-cli -q 1080 --dub"
alias zsha="cd ~/.zsh && nvim --noplugin aliases"
alias fishc="cd ~/.config/fish && nvim config.fish"
alias alac="nvim --noplugin ~/.config/alacritty/alacritty.toml"

alias ff="fastfetch"
alias sht="shutdown now"
alias dh="rm ~/.history.db"
alias sp="systemctl suspend"
alias rebootcmd="systemctl reboot"
alias fontcache="sudo fc-cache -f -v"
alias rex="xrdb -remove && xrdb -merge ~/.Xresources && kill -USR1 \$(pidof st)"

alias lzg="lazygit"

alias lzd="lazydocker"

alias ta="tmux attach"
alias tk="tmux kill-server"
alias tn="tmux new -s \$USER"

alias zls="ls \$ZPLUGINDIR"

alias motivation="mpv ~/Documents/github/media/videos/biy/cristiano.mp4"
