#!/usr/bin/env zsh

# weather
alias weather='curl -s "wttr.in/Tecoh,Yucatan"'

# main
alias l="less"
alias :q="exit"
alias lsi="ls -1"
alias wg="sudo wg"
alias sudo="sudo "
alias pass="gopass"
alias ff="fastfetch"
alias name="generate_name"
alias dh="rm ~/.history.db"
alias rbt="systemctl reboot"
alias xr="nvim ~/.Xresources"
alias c="xclip -selection clipboard"
alias fontcache="sudo fc-cache -f -v"
alias feh="feh -g 860x600 --scale-down"
alias p="xclip -selection clipboard -o"
alias calc="python -i -c 'import math, cmath; from math import *'"
alias rex="xrdb -remove && xrdb -merge ~/.Xresources && kill -USR1 \$(pidof st)"

# zsh
alias zshe="nvim ~/.zshenv"
alias zshc="cd ~/.zsh && nvim config"
alias zsha="cd ~/.zsh && nvim  aliases"

# power managment
alias sp="smart_power suspend"
alias rbt="smart_power restart"
alias sht="smart_power shutdown"

# lazygit
alias lzg="lazygit"
alias lzd="lazydocker"

# btm
alias btm="btm --basic"

# tmux
alias ta="tmux attach"
alias tn="tmux new -c \$HOME -s \$USER"
