#!/usr/bin/env zsh

autoload -Uz \
  url-quote-magic \
  edit-command-line

# Completions
zcompletions
zcompile-dump &|
zcompile-config &|

# Functions from ./functions
zle -N edit-command-line
zle -N smart-help
zle -N clear-and-redisplay
zle -N copy-terminal-buffer

# Path autocompletion
compdef _directories new

# Custom binds
bindkey -e # use emacs preset
bindkey '\eh' smart-help
bindkey '^[e' edit-command-line
bindkey '^L' clear-and-redisplay
bindkey '^X' copy-terminal-buffer
bindkey '^[[Z' reverse-menu-complete

# Zsh options
setopt \
  AUTO_CD \

# Completion configuration
zstyle ':completion:*' menu select
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'

# Nix shell indicator
if [[ -n "$IN_NIX_SHELL" ]]; then
  case "$IN_NIX_SHELL" in
    pure)   NIX_TAG="%F{green}[NIXSHELL:pure]%f " ;;
    impure) NIX_TAG="%F{yellow}[NIXSHELL:impure]%f " ;;
    *)      NIX_TAG="%F{green}[NIXSHELL]%f " ;;
  esac
else
  NIX_TAG=""
fi

# White prompt
PROMPT="${NIX_TAG}%F{white}%2~%f "

# Cached tool inits
zsh-cache-init fzf fzf --zsh
zsh-cache-init atuin atuin init zsh

# Disable "c-s delay"
stty -ixon
stty susp undef
