#!/usr/bin/env zsh

autoload -Uz \
  url-quote-magic \
  edit-command-line

# Completions
load_completions
zcompile_dump &|
zcompile_config &|

# Functions from ./functions
zle -N edit-command-line
zle -N smart-help
zle -N clear-and-redisplay
zle -N copy-terminal-buffer

# Path autocompletion
compdef _directories new

# Custom binds
bindkey -e # use emacs preset
bindkey '\eh' smart-help
bindkey '^[e' edit-command-line
bindkey '^L' clear-and-redisplay
bindkey '^X' copy-terminal-buffer
bindkey '^[[Z' reverse-menu-complete

# Zsh options
setopt \
  AUTO_CD \
  HIST_FIND_NO_DUPS \
  HIST_IGNORE_ALL_DUPS

# Disable native zsh history file
export HISTFILE=/dev/null

# Completion configuration
zstyle ':completion:*' menu select
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'

# White prompt
PROMPT='%F{white}%2~%f '

# Cached tool inits
zsh-cache-init fzf fzf --zsh
zsh-cache-init atuin atuin init zsh
zsh-cache-init zoxide zoxide init zsh
zsh-cache-init mise mise activate zsh

# Disable "c-s delay"
stty -ixon
stty susp undef
