typeset -g POWERLEVEL9K_SHORTEN_STRATEGY=truncate_to_last

typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIINS_CONTENT_EXPANSION=''
typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VICMD_CONTENT_EXPANSION=''
typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIVIS_CONTENT_EXPANSION=''

typeset -g POWERLEVEL9K_VCS_INCOMING_CHANGES_ICON=':'
typeset -g POWERLEVEL9K_VCS_OUTGOING_CHANGES_ICON=':'
