#!/usr/bin/sh

# main
alias n="nvim"
alias :q="exit"
alias yay="paru"
alias cl="clear"
alias sudo="sudo "
alias wg="sudo wg"
alias pass="gopass"
alias bb="btm --basic"
alias xresources="vi ~/.Xresources"
alias zsha="cd ~/zsh && vi aliases"
alias zshc="cd ~/zsh && vi zshconfig"
alias vi="NVIM_APPNAME='vim' nvim"
alias c="xclip -selection clipboard"
alias p="xclip -selection clipboard -o"
alias ani-cli="ani-cli -q 1080"
alias ani-cli-dub="ani-cli -q 1080 --dub"
alias fishc="cd ~/.config/fish && vi config.fish"
alias feh="feh -g 860x600 --scale-down"

alias ff="fastfetch"
alias sht="shutdown now"
alias dh="rm ~/.history.db"
alias sp="systemctl suspend"
alias rebootcmd="systemctl reboot"
alias fontcache="sudo fc-cache -f -v"
alias rex="xrdb -remove && xrdb -merge ~/.Xresources && kill -USR1 \$(pidof st)"

alias lzg="lazygit"
alias glfv="git ls-files -v"
alias glc="git rev-list --count HEAD"

alias lzd="lazydocker"

alias ta="tmux attach"
alias tk="tmux kill-server"
alias tn="tmux new -s \$USER"

alias zls="ls \$ZPLUGINDIR"

alias m="cd /run/media"

alias motivation="mpv ~/Documents/github/media/videos/biy/cristiano.mp4"
