#!/bin/env sh

y() {
	tmp="$(mktemp -t "yazi-cwd.XXXXXX")"
	yazi "$@" --cwd-file="$tmp"
	if cwd="$(cat -- "$tmp")" && [ "$cwd" != "" ] && [ "$cwd" != "$PWD" ]; then
		cd -- "$cwd" || return
	fi
	rm -f -- "$tmp"
}

keys() {
	xev | awk -F'[ )]+' '/^KeyPress/ { a[NR+2] } NR in a { printf "%-3s %s\n", $5, $8 }'
}

rez() {
	. /home/bryant/.zshrc
}

grubupdate() {
	sudo grub-mkconfig -o /boot/grub/grub.cfg
}

dotsstow() {
	dots="$HOME/Documents/github/dotfiles"
	mkdir -p "$dots" && cd "$dots" || return
	stow --dir="$dots" --target=/home/"$USER" --adopt --restow .

	cd - || return # get back to previous dir

	# the "." at the end it is important, because stow needs to know which files
	# you want to add to the "--target" folder. If not, then no dir nor file will
	# be symlinked
}

# NOTE: this is to refresh DNS cache. I have this because I have
# blocked all social media and manga websites to avoid get distracted
# while using my computer
dnscache() {
	sudo systemd-resolve --flush-caches
}

# NOTE: this function is used when inside tmux session.
# this script works along my custom tmux scripts in ~/bin/tmux
home() {
	if [ -z "$TMUX" ]; then
		printf "Not in a tmux session."
		return 1
	fi

	tmux_current_pane_path="$(tmux display-message -p '#{pane_current_path}')" || return 1
	tmux_current_session_path=$(tmux display-message -p '#{session_path}') || return 1

	if [ "$tmux_current_pane_path" = "$tmux_current_session_path" ]; then
		tmux display-message "You are already in your session root directory"
		return 0
	fi

	cd "$tmux_current_session_path" || {
		tmux display-message "Error: Could not change to session root: $tmux_current_session_path"
		return 1
	}
}

# NOTE: this function is used in ~/.zshconfig file
# is attached to ^L keybind
clear_and_redisplay() {
	clear
	zle .redisplay
}

# NOTE: this function is used in ~/.zshconfig file
# is attached to ^X keybind
copy_terminal_buffer() {
	echo "$BUFFER" | xclip -selection clipboard
	zle reset-prompt
}

# NOTE: this function is used in ~/.zshconfig file
# is attached to ^[h keybind
smart_help() {
	cmd="${BUFFER%% *}"

	if [ -z "$cmd" ] || [ -z "$BUFFER" ]; then
		return
	fi

	if man -w "$cmd" >/dev/null 2>&1; then
		BUFFER="MANPAGER='nvim +Man!' man $cmd"
		zle accept-line
	elif command -v "$cmd" >/dev/null 2>&1; then
		BUFFER="$cmd --help | less -F"
		zle accept-line
	else
		printf '\a'
	fi
}
