#!/usr/bin/env zsh

autoload -Uz \
	url-quote-magic \
	edit-command-line \
	compinit && compinit

# zsh widgets
zle -N edit-command-line
zle -N smart_help
zle -N clear_and_redisplay
zle -N copy_terminal_buffer

# zsh options
setopt AUTO_CD \
	HIST_FIND_NO_DUPS \
	HIST_IGNORE_ALL_DUPS \

# completion configuration
zstyle ':completion:*' menu select

zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'

# extend path
extra_path=(
	~/bin/global/
	~/.local/bin/
	~/.cargo/bin/
	~/bin/crontab/
	/usr/local/bin/
	/var/lib/flatpak/exports/bin/
	~/.local/share/nvim/mason/bin/
	~/Documents/github/boilerplate/
)

PROMPT='%F{white}%2~%f '

extra_path_expanded=$(printf "%s:" "${extra_path[@]}")
export PATH="${(j/:/)extra_path}:${PATH}"

# start software
eval "$(fzf --zsh)"
eval "$(atuin init zsh)"
eval "$(zoxide init zsh)"
eval "$(starship init zsh)"
eval "$(fnm env --use-on-cd)"


# custom plugin manager
# function can be found in ~/.zshplugin
repos=(
	hlissner/zsh-autopair
	jeffreytse/zsh-vi-mode
	# zsh-users/zsh-syntax-highlighting
)


# load plugins
plugin-load $repos

# share clipboard
ZVM_SYSTEM_CLIPBOARD_ENABLED=true

function zvm_after_init() {
	bindkey '\eh' smart_help
	bindkey '^[e' edit-command-line
	bindkey '^[l' clear_and_redisplay
	bindkey '^X' copy_terminal_buffer
	zvm_bindkey viins '^R' atuin-search
	zvm_bindkey vicmd '^R' atuin-search
	bindkey '^[[Z' reverse-menu-complete
}

# disable "c-s delay"
stty -ixon
stty susp undef
