#!/usr/bin/env zsh

autoload -Uz url-quote-magic edit-command-line compinit &&
	compinit

# zsh widgets
zle -N edit-command-line
zle -N smart_help
zle -N clear_and_redisplay
zle -N copy_terminal_buffer

bindkey -e
bindkey '\eh' smart_help
bindkey '^[e' edit-command-line
bindkey '^L' clear_and_redisplay
bindkey '^X' copy_terminal_buffer
bindkey '^[[Z' reverse-menu-complete

# zsh options
setopt AUTO_CD HIST_FIND_NO_DUPS HIST_IGNORE_ALL_DUPS

# completion configuration
zstyle ':completion:*' menu select

zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'

# extend path
extra_path=(
	~/bin/global/
	~/.local/bin/
	~/.cargo/bin/
	~/bin/crontab/
	/usr/local/bin/
	/var/lib/flatpak/exports/bin/
	~/.local/share/vim/mason/bin/
	~/.local/share/nvim/mason/bin/
	~/Documents/github/boilerplate/
)

PROMPT='%F{white}%2~%f '

extra_path_expanded=$(printf "%s:" "${extra_path[@]}")
export PATH="${(j/:/)extra_path}:${PATH}"

# custom plugin manager
# function can be found in ~/.zshplugin
repos=(
	hlissner/zsh-autopair
	# zsh-users/zsh-syntax-highlighting
)

# load plugins
plugin-load $repos

# start software
eval "$(fzf --zsh)"

eval "$(atuin init zsh)"
eval "$(starship init zsh)"
eval "$(fnm env --use-on-cd)"
eval "$(zoxide init zsh)"

# disable "c-s delay"
stty -ixon
stty susp undef
