# {{ enviroment variables

export EDITOR="nvim"
export VISUAL=$EDITOR
export TERMINAL="xterm"
export SUDO_EDITOR=$EDITOR
export BROWSER="firefox"
export VIDEO="mpv"
export COLORTERM="truecolor"
export OPENER="xdg-open"
export PAGER="bat"
export WM="dwm"
export GPG_TTY=$(tty)
export MANPAGER='nvim +Man!'
export GOPATH="/home/bryant/go/bin"
export CM_LAUNCHER="rofi"
export SXHKD_SHELL="zsh"
export STARSHIP_CONFIG="/home/bryant/.config/starship/starship.toml"
export XDG_CONFIG_HOME="$HOME/.config"

# }}

#{{ fzf

export FZF_DEFAULT_OPTS=" \
--height=50% \
--preview-window noborder \
--bind 'ctrl-o:execute(xdg-open {})' \
--bind 'ctrl-x:execute(xdg-default {})' \
--bind 'ctrl-u:execute($HOME/bin/tmux/tmux-new-session {} working)' \
"

export FZF_DEFAULT_COMMAND="fd \
  --type f \
  --strip-cwd-prefix \
  --hidden \
  --follow \
  --exclude=.git \
"

export QT_QPA_PLATFORMTHEME=qt6ct
